# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3090477cd6abf5cb10fdc4dcb418232b3f90e4546473cfcd5b8dc39bd8c34ec608011eff212206c9b118364b68fa8ab6e6b1d072c56100245341ab948bb98854

test:
  secret_key_base: 56d92e7cc1d9fbb733440dd33da334654087a106d9d5c1df7b8d1f8f49c00adab07ab85a650c4c3828ce684b763ddc7d7219f46a178aedbd8bd89c214586c74c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
